### ISSUE TITLE
JSON parsing error in Package Control

### ISSUE THREAD

**Issue by elyseholladay** [wbond/sublime_alignment#12]
Hey Will :)

I installed Package Control & then Alignment. Now I get this error every time I go to Package Control -> Install Package:
"Package Control: Error parsing JSON from repository: http://wbond.net/sublime_packages/alignment."

Not sure if this is an Alignment issue or a Package Control issue. I uninstalled/deleted Alignment but am still getting the error.

Elyse

**Comment by wbond** [comment]
Hey Elyse!

Most likely the URL (http://wbond.net/sublime_packages/alignment) got added to your list of custom repositories. If you go to Preferences > Package Settings > Package Control > Settings – User you can delete that URL from the "repositories" list.

**Comment by elyseholladay** [comment]
Thanks. I knew it was something simple like that, I just didn't think to look under Preferences. Solved :)
