### ISSUE TITLE
alignment in css with pseudoclasses

### ISSUE THREAD

**Issue by iamstarkov** [wbond/sublime_alignment#13]
If the alignment's parser encounters a word like <b>:hover</b> or <b>:focus</b>, the output text will be strange:
<img src=http://img205.imageshack.us/img205/6158/10a10463e3754bc486c0072.png />

There is no mechanism for regulating the situation in the plugin settings

**Comment by ghost** [comment]
There's really no sane way for a plugin to do this without writing a bunch of special cases or a full-blown parser for every language you want it to support.

**Comment by wbond** [comment]
Yeah, the alignment plugin is really meant to be an aide so that you don't have to manually insert a bunch of spaces when trying to line up a few different lines.

In this situation it requires you only select the two lines that should be lined up.
