### ISSUE TITLE
support key/value alignment

### ISSUE THREAD

**Issue by naonak** [wbond/sublime_alignment#2]
Support key/value alignment like : http://www.sublimetext.com/forum/viewtopic.php?f=5&t=1369

**Comment by wbond** [comment]
As of commit 29412f5e the settings now allows tweaking the characters used for mid-line alignment. Also, I added language-specific settings for JSON and Javascript to align the : character.

I also just released a package manager for Sublime Text 2 called Package Control that allows for automatic updating of Sublime Alignment. You can grab it from http://wbond.net/sublime_packages/package_control. Once you've manually upgraded Sublime Alignment through Package Control once, it will automatically install updates from then on.

**Comment by naonak** [comment]
Yeah!
