### ISSUE TITLE
There is no way to type localized A after instalation

### ISSUE THREAD

**Issue by marekkaczkowski** [wbond/sublime_alignment#21]
Shortcut CTRL+ALT+A lock posibility to type letter ą Ą ä Ä (AltGr (+ SHIFT) + A).

**Comment by wbond** [comment]
Hmm, I'm not sure of a good way to fix this. Do you have any suggestions?

**Comment by marekkaczkowski** [comment]
CTRL+ALT+G?

**Comment by wbond** [comment]
I am going to merge this discussion into #39
