### ISSUE TITLE
Auto alignment

### ISSUE THREAD

**Issue by alexwhitman** [wbond/sublime_alignment#22]
I don't know how possible this would be but it would great if aligned blocks could be monitored and then auto align if something changes.  For example, if I align some code and get the following:

```
$foo    = 1;
$foobar = 2;
```

then change `$foo` to `$something_really_long` then the block would automatically update to 

```
$something_really_long = 1;
$foobar                = 2;
```

without having to select and `Ctrl + Alt + A`.

**Comment by wbond** [comment]
I believe the ElasticTabstops package does what you are looking for: https://github.com/SublimeText/ElasticTabstops

**Comment by alexwhitman** [comment]
Unless I'm doing something wrong (possible) it only seems to work on tabs before any text, not spaces for alignment in the text.

**Comment by wbond** [comment]
It sounds like there may be a bug in the package. This is how it is supposed to work: http://nickgravgaard.com/elastictabstops/
