### ISSUE TITLE
suggestion: CSS vendor prefix alignment

### ISSUE THREAD

**Issue by Daniel-Hug** [wbond/sublime_alignment#24]
It'd be sweet if your plugin would change this:

<pre><code>-webkit-border-radius: 50%;
-moz-border-radius: 50%;
-ms-border-radius: 50%;
-o-border-radius: 50%;
border-radius: 50%;</code></pre>

into this:

<pre><code>-webkit-border-radius: 50%;
   -moz-border-radius: 50%;
    -ms-border-radius: 50%;
     -o-border-radius: 50%;
        border-radius: 50%;</code></pre>

...And change this:

<pre><code>background: -webkit-linear-gradient(top, #fff, #eee);
background: -moz-linear-gradient(top, #fff, #eee);
background: -ms-linear-gradient(top, #fff, #eee);
background: -o-linear-gradient(top, #fff, #eee);
background: linear-gradient(top, #fff, #eee);</code></pre>

into this:

<pre><code>background: -webkit-linear-gradient(top, #fff, #eee);
background:    -moz-linear-gradient(top, #fff, #eee);
background:     -ms-linear-gradient(top, #fff, #eee);
background:      -o-linear-gradient(top, #fff, #eee);
background:         linear-gradient(top, #fff, #eee);</code></pre>

**Comment by 37mm** [comment]
Seconded! That's my preferred alignment for vendor prefixes too.

**Comment by dreamgfx** [comment]
Add JS object also. Example:

``` javascript
 some_js_object{
               one : 'some string',
             other : 'other string here. It is very long string!',
         longIndex : 4
   }
```

 Align on ':' symbol.

**Comment by niksy** [comment]
Yes, this would be nice addition :)

**Comment by wbond** [comment]
This is really just a simple alignment plugin and it doesn't take into consideration language syntax at all.

I know there are quite a number of other alignment packages out there now - one of them may be able to easily accomplish this.
