### ISSUE TITLE
Doesn't work with ruby 1.9 hash notation

### ISSUE THREAD

**Issue by gdlx** [wbond/sublime_alignment#28]
Hi,

Aligment works fine with Ruby 1.8 Hash notation but not with 1.9. Example :

This works fine :

```
{
  :display_label => "name",
  :value => "John Doe"
}
```

This does nothing :

```
{
  display_label: "name",
  value: "John Doe"
}
```

**Comment by epitron** [comment]
I, too, would love to see this.

**Comment by kerrizor** [comment]
_blows dust off this issue_

:+1:

**Comment by epitron** [comment]
I've switched to https://github.com/jarod2d/sublime_valign/ which does it great.

**Comment by kerrizor** [comment]
Works like a charm, THANK YOU 💛

**Comment by epitron** [comment]
No problem! Issue (and project) closed.

**Comment by wbond** [comment]
If you open a file in any language, say Ruby, then go to Preferences > Settings - More > Syntax Specific - User. Inside of this settings file, you can dictate what characters are used for alignment. The following should probably do it. By default, it aligns on `=`.

``` json
{
    "alignment_chars": ["=", ":"]
}
```
