### ISSUE TITLE
Align `:`

### ISSUE THREAD

**Issue by MarioRicalde** [wbond/sublime_alignment#3]
Alignment of `:` is very useful when working with some languages (Sass to be specific) where you do declarations of variables like this:

```
$something : "cool";
$hello : "yay";
```

Would be awesome to provide this functionality by default :)

**Comment by MarioRicalde** [comment]
My god, I'm an idiot. Sorry about that.

**Comment by wbond** [comment]
I just released version 1.1.3 that adds : to the list of aligned characters for CSS. I presume that you are using CSS syntax for your SASS. If not, you'll need to add a SASS-specific settings file that adds the :.
