### ISSUE TITLE
Aligning by regex

### ISSUE THREAD

**Issue by contentfree** [wbond/sublime_alignment#35]
It would be great to have another command that aligns based on a regex which you're prompted for. This would be great for aligning multiple columns with a single multi-line selection (not a multi-caret selection).

It would also make aligning javascript objects easy (match /(?<=:) / or whatev)

**Comment by wbond** [comment]
I think for now with all of my other commitments I am going to stick with keeping this plugin simple.

There are a bunch of other alignment packages available now, and I think some of them allow using regex for alignment.
