### ISSUE TITLE
ST3 version?

### ISSUE THREAD

**Issue by quarnster** [wbond/sublime_alignment#36]
Pretty please :)

**Comment by mattstein** [comment]
+1

**Comment by benmatselby** [comment]
+1

**Comment by Geczy** [comment]
+1

Year old repo, doubt it'll happen

**Comment by kevinsperrine** [comment]
It's actually _extremely_ easy to port this to ST3. See my pull request #38

**Comment by mattstein** [comment]
Thanks Kevin, both for your work and for kindly letting me/us know about it!

**Comment by wbond** [comment]
Yeah, let's track this at #38.
