### ISSUE TITLE
not indenting properly

### ISSUE THREAD

**Issue by darkhouse** [wbond/sublime_alignment#4]
I just installed the package using Package Control (which is awesome). However, when I do a multi select, it ends up putting the tabs (or spaces) at the end of the lines and doesn't actually line up the equals signs. This happened on both Windows and OSX. Any thoughts?

**Comment by wbond** [comment]
Can you provide the text it is failing on and indicate where your cursors were placed?

**Comment by darkhouse** [comment]
Here's some text.

$config['smtp_timeout'] = '60';
$config['crlf'] = "\r\n";
$config['newline'] = "\r\n";
$config['charset'] = 'utf-8';
$config['wordwrap'] = TRUE;

I tried selecting everything and then doing a Ctrl+Shift+L to convert to 
multiple selection. I tried selecting each line individually to manually 
create a multiple selection. I tried putting my cursor at the first 
character and doing Ctrl+Alt+Down to column select all lines, then doing 
Ctrl+L to make it select the entire line for each. None seemed to help. 
It just puts the spaces or tabs on the end of each line.

Thanks.

**Comment by wbond** [comment]
For this type of alignment you either need to select all lines in a single selection and press ctrl+alt+a, or make multiple selections at the columns you want to align. It sounds like you were making multiple selections of each complete line, which would do exactly as you were experiencing, and align the final column.

If you want to align multiple selections (which in this case is more complicated than a single selection), try the following:
1. Select all lines in a single selection
2. Press ctrl+shift+l to split into a selection per line
3. Press home to go to the beginning of each line
4. Press ctrl+right until your cursors are positioned right before each =
5. Press ctrl+alt+a

**Comment by darkhouse** [comment]
Ah, ok. Doing a multi select from the start of each line to the equal 
sign worked. I thought it would evaluate each line and find the equal 
sign in it for me. Thanks!
