### ISSUE TITLE
Aligning Javascript var statements

### ISSUE THREAD

**Issue by DjebbZ** [wbond/sublime_alignment#41]
Hello,

I'd like to align a mutliline variables declaration in Javascript.

From :

``` javascript
var models = require('../models'),
    async = require('async'),
    http = require('http');
```

To :

``` javascript
var models = require('../models'),
    async  = require('async'),
    http   = require('http');
```

But the packages behaves like this when I select those 3 lines :

``` javascript
// First time I use the shortcut
    var models = require('../models'),
    async = require('async'),
    http = require('http');
```

Then :

``` javascript
// Second time I use the shortcut
    var models = require('../models'),
    async      = require('async'),
    http       = require('http');
```

Is it possible to achieve what I want ? Note that I also tried with JsFormat, without success. 2nd note : I installed Alignement with Package Control, so I should have the last version.

**Comment by vanrijn** [comment]
I think that if you set "align_indent": false, that might fix the thing you're seeing the first time you use the shortcut?

**Comment by wbond** [comment]
I'm not currently planning on adding language semantics to the plugin - it really is just a simple (read: dumb) plugin to  line up the left edge of a bunch of lines, equal signs, or multiple cursors.

I know there are quite a number of other alignment packages now that allow for complex rules and one of those might fit the bill for you.
