### ISSUE TITLE
Can't align commas?

### ISSUE THREAD

**Issue by DaveSanders** [wbond/sublime_alignment#48]
I'm not sure what I'm doing wrong, but is there something that keeps it from aligning commas?

I want to align:
      [ 1, '01_home.png', 'Home', 'The guest home page'],
      [ 2, '02_login.png', 'Login', 'The login form'],

in an array on the commas.  My only change to my config is:

{
  "alignment_chars": ["=", ","]
}

What am I missing?

**Comment by DaveSanders** [comment]
Or maybe I'm just not understanding how it works.  if my FIRST comma is misaligned, its fixing that, but repeated use isn't lining up the others?

**Comment by wbond** [comment]
Yeah, really Alignment if for simple alignment using very basic rules. It does not take into account language structure in any way.

There are quite a number of different alignment packages available now - one of those may fit the bill for you.

**Comment by DaveSanders** [comment]
Thanks. Any suggestions?

**Comment by wbond** [comment]
I'd go to http://wbond.net/sublime_packages/community and search for "Align"

**Comment by zchrykng** [comment]
@DaveSanders I use https://github.com/khiltd/Abacus It might do what you want.
