### ISSUE TITLE
How align compass include

### ISSUE THREAD

**Issue by miguelsmuller** [wbond/sublime_alignment#50]
how do I align from the first parenthesis?

color: #636363;
font-weight: 600;
margin-bottom: 0;
@include background-image (linear-gradient(top, #FDFDFD, #EAEAEA));
@include text-shadow (0 1px #FFF);

**Comment by wbond** [comment]
No, there is no way to do this. Alignment is really for simple alignment tasks and does not take into account language structure in any way.

I think there are a bunch of other packages that allow for complex alignment rules that may help with accomplishing what you want.

**Comment by miguelsmuller** [comment]
any suggestions ?

**Comment by wbond** [comment]
I'd search at http://wbond.net/sublime_packages/community
