### ISSUE TITLE
Appears mis-aligned in ST3 but fine in Vim

### ISSUE THREAD

**Issue by sjclt-wp** [wbond/sublime_alignment#55]
Code doesn't appear to align correctly in ST3, but looks fine in Vim.  As seen in the attached image, the two lower chunks of code have been aligned with cmd+ctrl+a but I can't tell from looking in ST3.  

ST3 is on left, Vim on right.  This is on an iMac.  Works great on my Ubuntu machine.  Any thoughts?

![alignment](https://f.cloud.github.com/assets/5561973/1230548/d3817ce8-27e3-11e3-982c-ca16c8fce94d.png)

Installed Packages:

AdvancedNewFile
Alignment
BracketHighlighter
DocBlockr
Emmet
Git
HTML5
jQuery
PHPUnit
SendToPastebin
Theme - Soda
Tomorrow Color Schemes
TrailingSpaces
Wordpress
WordPress Generate Salts

**Comment by curtisblackwell** [comment]
It looks like your font isn't monospace… Change your font setting to a monospace font.

**Comment by wbond** [comment]
Yeah, it appears you are using a variable-width font. Not something the Alignment package can fix.
