### ISSUE TITLE
Chinese Line can not alignment, because chinese characters are twice as wide as the english alphabet

### ISSUE THREAD

**Issue by laurenceqi** [wbond/sublime_alignment#56]
Chinese Line can not alignment, because chinese characters are twice as wide as the english alphabet

**Comment by wbond** [comment]
Can you provide some examples?

**Comment by g8up** [comment]
@wbond , I supply an example below
```javascript
const Me = {
	"我的名字": 'g8up',
	"年龄"  : 18,
	'我的老家': '就是这个屯儿',
};
```

**Comment by CoffeeKoala** [comment]
I would like to know if this issuse is fixed or not?
