### ISSUE TITLE
Wont work for "font_face": "Ubuntu Mono",

### ISSUE THREAD

**Issue by uschen** [wbond/sublime_alignment#58]
when using

```
"font_face": "Ubuntu Mono",
```

text wont get aligned

**Comment by uschen** [comment]
it's not the "text" that are unable to getting aligned (after changing the font, without doing anything, the previous failed text get aligned), instead, it seems Ubuntu Mono has some weird char width

**Comment by wbond** [comment]
Ok, it sounds like it is not a problem with Alignment then.
