### ISSUE TITLE
Backbone.js like Patterns

### ISSUE THREAD

**Issue by rc1** [wbond/sublime_alignment#6]
Hi, 

This feature doesn't work when using patterns like those used with Backbone.js. For example:

```
var View = Backbone.View.extend({

    events : {
        "click somewhere" : "then",
        "touch there" : "that"
    },

    initialize : function (opts) {

        this.options = _.extend({
            key : "value",
            bigger : "value"
        }, opts);
    }

});
```

Won't work, unless I am missing something?

Thanks, would be great to be able to use this with the above.

**Comment by wbond** [comment]
This package is really just for aligning things in a strait line.

For your needs I would check out the JsFormat package via Package Control, or you can edit the "JavaScript Indent.tmPreferences" file in the "JavaScript" package directory to indent as you write. You can get to your Packages directory via the "Preferences > Browse Packages…" menu.
