### ISSUE TITLE
Key bindings not working when SublimeLinter is installed

### ISSUE THREAD

**Issue by cmdrrobin** [wbond/sublime_alignment#61]
Alignment and SublimeLinter packages doesn't work together properly. (at least not under Sublime Text 3)
They use both the same keybindings. When trying to override it with customer (user) keybinding, nothing happens.

**Comment by nicinabox** [comment]
FWIW I disabled the keybinding for SublimeLinter and Alignment started working after a restart.

**Comment by jomo** [comment]
Same here, but the problem was caused by the [LiveStyle](http://livestyle.emmet.io/) plugin. I didn't need it anymore so I removed it, that solved it for me.

**Comment by wbond** [comment]
I dunno if I can solve this. Alignment has been around for a really long time, so it would seem odd to just change the key bindings because another package decided to use them also.

Perhaps add a new mapping in your Key Bindings - User file?
