### ISSUE TITLE
LESS alignment issue

### ISSUE THREAD

**Issue by lombardi-gux** [wbond/sublime_alignment#67]
I got the plugin to work in LESS, thanks.  One issue remains, not sure how to handle with current settings:

I frequently have code like

```
        &:last-child {
            border-bottom-left-radius: 0;
            border-top-left-radius: 0;
            border-left: none;
        }
        &:first-child {
            border-bottom-right-radius: 0;
            border-top-right-radius: 0;
            border-right: none;
        }
```

which aligns to

```
        &                             :last-child {
            border-bottom-left-radius : 0;
            border-top-left-radius    : 0;
            border-left               : none;
        }
        &                             :first-child {
            border-bottom-right-radius: 0;
            border-top-right-radius   : 0;
            border-right              : none;
        }
```

I would rather ignore the ":" in the pseudo-selector and keep them `&:first-child` whilst aligning all the other colons.

**Comment by wbond** [comment]
I don't plan on implementing this with Alignment. What you are looking for is not to align characters, but to format code based on syntax information. Since Alignment is not a code parser, it won't be able to accomplish this.
