### ISSUE TITLE
String object keys with colons are aligned inside the keyname

### ISSUE THREAD

**Issue by DanielSmedegaardBuus** [wbond/sublime_alignment#68]
Hi :)

Just came across this funky little thing. Alignment will align inside object keys if they're string literals with a colon inside them. E.g.:

```
var obj = {
    key   : 'val',
    'with :colon' : 'val'
};
```

**Comment by wbond** [comment]
Yes, alignment is really a simple package and is not syntax or language aware. For complicated alignment, I usually use `Selection > Split Into Lines` and then `Expand Selection to Scope` to traverse strings, then Alignment to align the cursors.

Alternatively there are a number of other alignment plugins that allow for more complicated rules. https://packagecontrol.io/search/align
