### ISSUE TITLE
No lint errors.on ST3 Mac OSX

### ISSUE THREAD

**Issue by SwithFr** [wbond/sublime_alignment#69]
When I want to align some lines I've that error : " No lint errors."

**Comment by thangkieu** [comment]
I got the same issue. Please help to resolve it
Thank a lot.

**Comment by Pendrokar** [comment]
"No lint errors." is an error thrown by a different package called Sublime Linter.

> { "keys": ["ctrl+super+a"], "command": "sublimelinter_show_all_errors" }
> ...
> { "keys": ["super+ctrl+a"], "command": "alignment" }

The default key that is set for OSX is the same as the one set for Alignment.

The workaround is to edit the keybindings under Preferences -> Package settings -> Alignment -> Key bindings (User)

By copying the keybind from the nearby (Default) keybindings file and saving that.

This is probably a "won't fix" issue.

**Comment by SwithFr** [comment]
Thanks Pendrokar !
