### ISSUE TITLE
Config conflict with Docblokr

### ISSUE THREAD

**Issue by it-can** [wbond/sublime_alignment#70]
The config file Alignment and DocBlokr are the same filename... Please fix! See also:

https://github.com/spadgos/sublime-jsdocs/issues/294

**Comment by wbond** [comment]
I don't understand what the issue is? That file you reference is the base file-type settings file. Since Alignment allows settings specified per syntax, I can't have just an `Alignment.sublime-settings`.

**Comment by it-can** [comment]
ok so I need to add the config of Alignment to the Base File of Docblokr?

**Comment by wbond** [comment]
Well, that config file is for all of Sublime Text, not just Docblockr or Alignment. You can set any of the global settings to it, such as `font_size`, `draw_white_space`, etc.
