### ISSUE TITLE
Indent partially before special chars.

### ISSUE THREAD

**Issue by willstott101** [wbond/sublime_alignment#75]
I'd have loved this to right-align the variable names: http://puu.sh/fJ4Op/0a65d24a07.png Instead of just the equals signs. As far as I can tell, partial selects on several lines won't conflict.

If this is possible with the current version I'd be interested to hear how.

**Comment by wbond** [comment]
It sounds like you probably want a language-aware alignment tool, or a tool that has advanced rules/regex.

Unfortunately Alignment can't do this now, and I think there are other packages like https://packagecontrol.io/packages/AlignTab and https://packagecontrol.io/packages/Abacus that will probably suit your needs.
