### ISSUE TITLE
mac key binding beeps, does not indent

### ISSUE THREAD

**Issue by jm3** [wbond/sublime_alignment#77]
after a default install of Sublime Text and Package Control (no other packages), and selecting this block:

```
foo = bar
thing = other thing
```

and pressing `cmd-alt-a`, Sublime Text just beeps and indents nothing.

(OTOH, using the context-menu **Align By : First =** works fine and aligns the block)

**Comment by wbond** [comment]
I think this means that OS X is intercepting the key binding, however I believe the keybinding on OS X is ctrl+cmd+a.
