### ISSUE TITLE
Aligning is indenting every single line to the right

### ISSUE THREAD

**Issue by spengilley** [wbond/sublime_alignment#81]
Aligning a second time does align the = symbols correctly, however it still leaves all of the lines starting halfway across the editor :)

**Comment by wbond** [comment]
Can you provide example input and output?

**Comment by spengilley** [comment]
Hi there,

Take the following php…

![screen shot 2015-09-11 at 14 45 35](https://cloud.githubusercontent.com/assets/749260/9816331/4ac48966-5894-11e5-8fec-6c0907af80c6.png)

Select all of it and press Shift + cmd + a;

![screen shot 2015-09-11 at 14 47 12](https://cloud.githubusercontent.com/assets/749260/9816347/51b33b96-5894-11e5-87a0-d3b694700c48.png)

**Comment by wbond** [comment]
Your comment did not include the PHP.

**Comment by spengilley** [comment]
Try now :)

**Comment by wbond** [comment]
The Alignment plugin is not language aware - it is rather simple. In this situation you need to just select the two lines you want aligned.

The first time to press the key combo it will align the left margin of all selected lines, or align the `=` signs. If the first time it fixes the left margin, the second time will align the `=`.
