### ISSUE TITLE
Plugin doesn't work when I select the text.

### ISSUE THREAD

**Issue by Kristinita** [wbond/sublime_alignment#86]
### Summary

Plugin doesn't work when I select the text and run `alignment` command.
### Expected behavior

Alignment when I select text
### Actual behavior

Not alignment when I select text
### Steps to reproduce

I checked on plain Sublime Text Portable without plugins. 

My JavaScript code:

```
Tween.prototype = {
    constructor: Tween,
    init: function(elem, options, prop, end, easing, unit) {
    this.elem = elem;                                                                                
    this.prop = prop;                                                                                
    this.easing = easing || jQuery.easing._default;                    
    this.options = options;                                                                    
    this.start = this.now = this.cur();                                            
    this.end = end;                                                                                    
    this.unit = unit || (jQuery.cssNumber[prop] ? "" : "px");
    },                                                                                                              
    cur: function() {                                                                                
    var hooks = Tween.propHooks[this.prop];
```

I allocate a text site, I press <kbd>Ctrl+Alt+A</kbd>, but nothing occurs:

![Not Alignment](http://i.imgur.com/jGmYnx2.gif)

The console shows that at me everything is all right.

```
key evt: control+alt+a
command: alignment
```

If I allocate CSS-code, the plugin too doesn't work.

But if I clamp the <kbd>Ctrl</kbd> key and insert multiple cursors, the plugin works.

![Alignment](http://i.imgur.com/0Vf5syW.gif)
### Environment
- Operating system and version:  
    [√] Windows 10 Education
  - [ ] Mac OS ...
  - [ ] Linux ...
- Sublime Text:
  - Build 3114

**Comment by wbond** [comment]
You see to be doing a multi-cursor selection in the first example. Just do a single selection of all the lines you want to align.

**Comment by Kristinita** [comment]
@wbond, I squeezed the middle mouse button, it could not be done. Thank you very much!
