### ISSUE TITLE
Package is in "MISSING" state on Package Control at the moment (can't install via that way)

### ISSUE THREAD

**Issue by fgimian** [wbond/sublime_alignment#88]
Hey there Will, hope you're well.

I just re-installed Sublime and notice that I couldn't install Alignment.  The current state on the [Package Control website](https://packagecontrol.io/packages/Alignment) is **MISSING**.

Would you kindly check this out please?

Thanks heaps!
Fotis

**Comment by wbond** [comment]
This was resolved a little while ago, enjoy!

**Comment by fgimian** [comment]
Thanks mate! 😄
